name: Daily Cricket Update

on:
  schedule:
    - cron: '0 0 * * *' # Ye har roz Pakistani waqt ke mutabiq subah 5 baje khud chalega
  workflow_dispatch: # Iska fayda ye hai ke aap GitHub par button daba kar khud bhi chala sakte hain

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_matches.py
        env:
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}

      - name: Commit and Push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add matches.json
          git commit -m "Automated Match Update"
          git push
